version: '3'

services:
  service_client:
    build:
      context: .
      dockerfile: service_client/Dockerfile
    container_name: client
    command: python main_client.py
    volumes:
      - ./service_client/:/app/
      - ./pb/:/pb
    ports:
      - "7000:7000"
    networks:
      - grpc
  service_server:
    build:
      context: .
      dockerfile: service_server/Dockerfile
    container_name: server
    command: python main_server.py
    volumes:
      - ./service_server/:/app/
      - ./pb/:/pb
    ports:
      - "50051:50051"
    networks:
      - grpc

networks:
   grpc:
       driver: bridge
