# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: main.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='main.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nmain.proto\"\x1d\n\x0eMessageRequest\x12\x0b\n\x03tag\x18\x01 \x01(\t\"\x1f\n\x0fMessageResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\"+\n\x0bMenuRequest\x12\x0b\n\x03tag\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\x03\"`\n\x0cMenuResponse\x12%\n\x07results\x18\x01 \x03(\x0b\x32\x14.MenuResponse.Button\x1a)\n\x06\x42utton\x12\r\n\x05title\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61llback\x18\x02 \x01(\t2e\n\x06\x42otAPI\x12\x31\n\nGetMessage\x12\x0f.MessageRequest\x1a\x10.MessageResponse\"\x00\x12(\n\x07GetMenu\x12\x0c.MenuRequest\x1a\r.MenuResponse\"\x00\x62\x06proto3'
)




_MESSAGEREQUEST = _descriptor.Descriptor(
  name='MessageRequest',
  full_name='MessageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tag', full_name='MessageRequest.tag', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=43,
)


_MESSAGERESPONSE = _descriptor.Descriptor(
  name='MessageResponse',
  full_name='MessageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='MessageResponse.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=76,
)


_MENUREQUEST = _descriptor.Descriptor(
  name='MenuRequest',
  full_name='MenuRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tag', full_name='MenuRequest.tag', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='MenuRequest.user_id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=121,
)


_MENURESPONSE_BUTTON = _descriptor.Descriptor(
  name='Button',
  full_name='MenuResponse.Button',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='MenuResponse.Button.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='callback', full_name='MenuResponse.Button.callback', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=219,
)

_MENURESPONSE = _descriptor.Descriptor(
  name='MenuResponse',
  full_name='MenuResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='results', full_name='MenuResponse.results', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_MENURESPONSE_BUTTON, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=219,
)

_MENURESPONSE_BUTTON.containing_type = _MENURESPONSE
_MENURESPONSE.fields_by_name['results'].message_type = _MENURESPONSE_BUTTON
DESCRIPTOR.message_types_by_name['MessageRequest'] = _MESSAGEREQUEST
DESCRIPTOR.message_types_by_name['MessageResponse'] = _MESSAGERESPONSE
DESCRIPTOR.message_types_by_name['MenuRequest'] = _MENUREQUEST
DESCRIPTOR.message_types_by_name['MenuResponse'] = _MENURESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MessageRequest = _reflection.GeneratedProtocolMessageType('MessageRequest', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEREQUEST,
  '__module__' : 'main_pb2'
  # @@protoc_insertion_point(class_scope:MessageRequest)
  })
_sym_db.RegisterMessage(MessageRequest)

MessageResponse = _reflection.GeneratedProtocolMessageType('MessageResponse', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGERESPONSE,
  '__module__' : 'main_pb2'
  # @@protoc_insertion_point(class_scope:MessageResponse)
  })
_sym_db.RegisterMessage(MessageResponse)

MenuRequest = _reflection.GeneratedProtocolMessageType('MenuRequest', (_message.Message,), {
  'DESCRIPTOR' : _MENUREQUEST,
  '__module__' : 'main_pb2'
  # @@protoc_insertion_point(class_scope:MenuRequest)
  })
_sym_db.RegisterMessage(MenuRequest)

MenuResponse = _reflection.GeneratedProtocolMessageType('MenuResponse', (_message.Message,), {

  'Button' : _reflection.GeneratedProtocolMessageType('Button', (_message.Message,), {
    'DESCRIPTOR' : _MENURESPONSE_BUTTON,
    '__module__' : 'main_pb2'
    # @@protoc_insertion_point(class_scope:MenuResponse.Button)
    })
  ,
  'DESCRIPTOR' : _MENURESPONSE,
  '__module__' : 'main_pb2'
  # @@protoc_insertion_point(class_scope:MenuResponse)
  })
_sym_db.RegisterMessage(MenuResponse)
_sym_db.RegisterMessage(MenuResponse.Button)



_BOTAPI = _descriptor.ServiceDescriptor(
  name='BotAPI',
  full_name='BotAPI',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=221,
  serialized_end=322,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetMessage',
    full_name='BotAPI.GetMessage',
    index=0,
    containing_service=None,
    input_type=_MESSAGEREQUEST,
    output_type=_MESSAGERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetMenu',
    full_name='BotAPI.GetMenu',
    index=1,
    containing_service=None,
    input_type=_MENUREQUEST,
    output_type=_MENURESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BOTAPI)

DESCRIPTOR.services_by_name['BotAPI'] = _BOTAPI

# @@protoc_insertion_point(module_scope)
